# Copyright 2025, Command Line Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2
project_name: outrig

before:
    hooks:
        - npm ci
        - task build:frontend

builds:
    - id: outrig
      main: ./main-server.go
      dir: ./server
      binary: outrig
      ldflags:
          - -X main.OutrigVersion={{.Version}} -X main.OutrigBuildTime={{.Timestamp}} -X main.OutrigCommit={{.ShortCommit}}
      goos:
          - linux
          - darwin
      goarch:
          - amd64
          - arm64
      env:
          - CGO_ENABLED=0

archives:
    - id: default
      name_template: >
          {{- .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end -}}
      wrap_in_directory: true
      files:
          - LICENSE
          - README.md
          - NOTICE

checksum:
    name_template: "checksums.txt"
    extra_files:
        - glob: ./dist/homebrew/Formula/*.rb

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^ci:"
            - Merge pull request
            - Merge branch

release:
    draft: true
    extra_files:
        - glob: ./dist/homebrew/Formula/*.rb

notarize:
    macos:
        - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
          ids:
              - outrig
          sign:
              certificate: "{{ .Env.MACOS_SIGN_P12 }}"
              password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
          notarize:
              key: "{{ .Env.MACOS_NOTARY_KEY }}"
              key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
              issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"

brews:
    - repository:
          owner: outrigdev
          name: homebrew-outrig
          token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      homepage: "https://github.com/outrigdev/outrig"
      description: "Observability monitor for Go programs during development time"
      license: "Apache-2.0"
      directory: Formula
      install: |
          bin.install "outrig"
      test: |
          system "#{bin}/outrig", "version"
      service: |
          sockets "tcp://127.0.0.1:5005"
          run [opt_bin/"outrig", "server"]
          keep_alive false
          log_path var/"log/outrig.log"
          error_log_path var/"log/outrig.log"
          working_dir var
      caveats: |
          Outrig has been installed successfully!

          Quick start and docs:
          https://outrig.run/docs/quickstart

          To start the Outrig server manually (foreground):
            outrig server

          To load and start Outrig as a background service (recommended):
            brew services start outrig

          ---
          Outrig is open source and free for individual users.
          If you find it useful, please star us on GitHub:
            https://github.com/outrigdev/outrig
          ---

nfpms:
    - package_name: outrig
      homepage: "https://github.com/outrigdev/outrig"
      description: "Real-time debugging for Go programs, similar to Chrome DevTools"
      maintainer: "Outrig Dev <info@outrig.dev>"
      license: "Apache-2.0"
      vendor: "Outrig Dev"
      formats:
          - deb
          - rpm
      bindir: /usr/bin
      contents:
          - src: LICENSE
            dst: /usr/share/doc/outrig/LICENSE
          - src: README.md
            dst: /usr/share/doc/outrig/README.md
      recommends:
          - git
