version: "3"

tasks:
    dev:vite:
        desc: Run the Vite development server
        cmds:
            - npm run dev

    dev:
        desc: Run the Go server in development mode
        cmds:
            - OUTRIG_DEV=1 go run server/main-server.go server

    build:frontend:
        desc: Build the frontend for production
        cmds:
            - npm run build
            - mkdir -p server/pkg/web/dist
            - cp -r dist/* server/pkg/web/dist/

    build:server:
        desc: Build the Go server with embedded frontend
        deps: [build:frontend]
        cmds:
            - mkdir -p bin/
            - go build -ldflags "-X main.OutrigBuildTime=$(date +%Y%m%d%H%M%S)" -o bin/outrig server/main-server.go

    build:
        desc: Build everything for production
        cmds:
            - task: build:server

    prod:
        desc: Run the production server
        deps:
            - build
        cmds:
            - ./bin/outrig server

    generate:
        desc: Generate RPC code (Go/TypeScript)
        cmds:
            - go run cmd/generatego/main-generatego.go
            - go run cmd/generatets/main-generatets.go

    testrun:
        desc: run main-test.go to generate some fake data
        cmds:
            - go run server/main-server.go --dev run cmd/test/main-test.go

    testsmall:
        desc: run main-testsmall.go to generate minimal test data
        cmds:
            - go run cmd/testsmall/main-testsmall.go
