version: "3"

tasks:
    dev:vite:
        desc: Run the Vite development server
        cmds:
            - npm run dev

    dev:
        desc: Run the Go server in development mode
        cmds:
            - mkdir -p server/pkg/web/dist
            - touch server/pkg/web/dist/.gitkeep
            - OUTRIG_DEV=1 go run -ldflags "-X main.OutrigBuildTime=$(date +%Y%m%d%H%M%S) -X main.OutrigCommit=$(git rev-parse --short HEAD)" server/main-server.go monitor

    clean:webdist:
        desc: Clean the web embed directory for Go server
        cmds:
            - rm -rf server/pkg/web/dist
            - mkdir -p server/pkg/web/dist
            - touch server/pkg/web/dist/.gitkeep

    clean:
        desc: Clean build artifacts
        deps: [clean:webdist]
        cmds:
            - rm -rf dist dist-fe

    build:frontend:
        desc: Build the frontend for production
        deps: [clean]
        cmds:
            - npm run build
            - cp -r dist-fe/* server/pkg/web/dist/

    build:server:
        desc: Build the Go server with embedded frontend
        deps: [build:frontend]
        cmds:
            - mkdir -p bin/
            - go build -ldflags "-X main.OutrigBuildTime=$(date +%Y%m%d%H%M%S) -X main.OutrigCommit=$(git rev-parse --short HEAD)" -o bin/outrig server/main-server.go

    build:linuxserver:
        desc: Build the Go server for Linux (for Docker testing)
        cmds:
            - mkdir -p bin/
            - GOOS=linux GOARCH=$(go env GOARCH) go build -ldflags "-X main.OutrigBuildTime=$(date +%Y%m%d%H%M%S) -X main.OutrigCommit=$(git rev-parse --short HEAD)" -o bin/outrig-linux server/main-server.go

    build:
        desc: Build everything for production
        cmds:
            - task: build:server

    build:macos-app:
        desc: Build the complete macOS app bundle
        cmds:
            - task: build:server
            - task: build:outrigapp
            - task: build:app-bundle
            - echo "✅ macOS app bundle built successfully at dist/Outrig.app"

    prod:
        desc: Run the production server
        deps:
            - build
        cmds:
            - OUTRIG_NOTELEMETRY=1 ./bin/outrig server

    generate:
        desc: Generate RPC code (Go/TypeScript)
        cmds:
            - go run server/cmd/generatego/main-generatego.go
            - go run server/cmd/generatets/main-generatets.go

    test:run:
        desc: run main-test.go to generate some fake data
        cmds:
            - go run server/cmd/test/main-test.go

    test:small:
        desc: run main-testsmall.go to generate minimal test data
        cmds:
            - OUTRIG_DEVCONFIG=1 go run server/cmd/testsmall/main-testsmall.go

    test:docker:
        deps: [build:linuxserver]
        cmds:
            - docker build -t outrig-test -f testfiles/docker/Dockerfile .
            - docker run --rm outrig-test

    test:noop:
        desc: build main-testsmall.go with +no_outrig
        cmds:
            - go run -tags no_outrig server/cmd/testsmall/main-testsmall.go

    release:check:
        desc: Check if the GoReleaser configuration is valid
        cmds:
            - goreleaser check

    release:local:
        desc: Build a local release for testing (no publishing)
        cmds:
            - goreleaser release --snapshot --clean

    release:
        desc: Create and publish a new release
        cmds:
            - goreleaser release --clean

    install:
        desc: Build and install outrig to ~/.local/bin
        deps:
            - build
        cmds:
            - mkdir -p ~/.local/bin
            - cp bin/outrig ~/.local/bin/
            - chmod 755 ~/.local/bin/outrig
            - echo "Outrig installed to ~/.local/bin/outrig"

    updateversions:
        desc: Set the Outrig version in both server and SDK
        vars:
            VERSION: "{{.CLI_ARGS}}"
        cmds:
            # Check if version starts with v0.
            - |
                if [[ ! "{{.VERSION}}" =~ ^v0\. ]]; then
                  echo "❌ Error: Version must start with 'v0.' but got '{{.VERSION}}'"
                  exit 1
                fi
            - echo "Setting Outrig version to {{.VERSION}}"
            - sed -i.bak 's/var OutrigServerVersion = ".*"/var OutrigServerVersion = "{{.VERSION}}"/' server/pkg/serverbase/serverbase.go && rm server/pkg/serverbase/serverbase.go.bak
            - sed -i.bak 's/const OutrigSDKVersion = ".*"/const OutrigSDKVersion = "{{.VERSION}}"/' pkg/config/config.go && rm pkg/config/config.go.bak
            - sed -i.bak 's/OutrigAppVersion = ".*"/OutrigAppVersion = "{{.VERSION}}"/' macosapp/main-outrigapp.go && rm macosapp/main-outrigapp.go.bak
            # Update version in package.json and Info.plist (strip the 'v' prefix if present)
            - |
                VERSION_NO_V=$(echo "{{.VERSION}}" | sed 's/^v//')
                sed -i.bak 's/"version": ".*"/"version": "'$VERSION_NO_V'"/' package.json && rm package.json.bak
                sed 's/VERSION_PLACEHOLDER/'$VERSION_NO_V'/g' macosapp/assets/Info.plist.template > macosapp/assets/Info.plist
            - echo "✅ Version updated to {{.VERSION}} in server, SDK, package.json, and Info.plist"

    build:outrigapp:
        desc: Build the macOS systray app
        cmds:
            - mkdir -p bin/
            - cd macosapp && CGO_ENABLED=1 go build -o ../bin/outrigapp main-outrigapp.go

    build:app-bundle:
        desc: Create a macOS .app bundle with autoupdater
        deps: [build:server, build:outrigapp]
        cmds:
            - mkdir -p dist/Outrig.app/Contents/{MacOS,Resources}
            - cp bin/outrigapp dist/Outrig.app/Contents/MacOS/
            - cp bin/outrig dist/Outrig.app/Contents/MacOS/
            - chmod +x dist/Outrig.app/Contents/MacOS/outrigapp
            - chmod +x dist/Outrig.app/Contents/MacOS/outrig
            - cp macosapp/assets/Info.plist dist/Outrig.app/Contents/
            - cp macosapp/assets/outrig.icns dist/Outrig.app/Contents/Resources/AppIcon.icns
            - task: build:autoupdater
            - echo "✅ Created app bundle at dist/Outrig.app"

    build:autoupdater:
        desc: Build the Swift-based autoupdater for macOS and install to app bundle
        cmds:
            - cd macosapp/autoupdater && swift build -c release
            - |
                BINARY_PATH=$(cd macosapp/autoupdater && swift build -c release --show-bin-path)/OutrigUpdater
                SPARKLE_PATH=$(cd macosapp/autoupdater && swift build -c release --show-bin-path)/Sparkle.framework
                if [ -d "dist/Outrig.app/Contents/MacOS" ]; then
                  # Copy the updater binary
                  cp "$BINARY_PATH" dist/Outrig.app/Contents/MacOS/OutrigUpdater
                  chmod +x dist/Outrig.app/Contents/MacOS/OutrigUpdater
                  
                  # Create Frameworks directory and copy Sparkle.framework
                  mkdir -p dist/Outrig.app/Contents/Frameworks
                  cp -R "$SPARKLE_PATH" dist/Outrig.app/Contents/Frameworks/
                  
                  # Fix the rpath in the OutrigUpdater binary to point to the Frameworks directory
                  install_name_tool -add_rpath "@executable_path/../Frameworks" dist/Outrig.app/Contents/MacOS/OutrigUpdater
                  
                  echo "✅ Built and installed autoupdater to dist/Outrig.app/Contents/MacOS/OutrigUpdater"
                  echo "✅ Copied Sparkle.framework to dist/Outrig.app/Contents/Frameworks/"
                  echo "✅ Fixed rpath for OutrigUpdater to find Sparkle.framework"
                else
                  echo "✅ Built autoupdater at: $BINARY_PATH"
                  echo "✅ Built Sparkle.framework at: $SPARKLE_PATH"
                  echo "Note: App bundle not found. Run 'task build:app-bundle' to create a complete app bundle."
                fi

    create:icns:
        desc: Create an .icns file from the PNG icon
        cmds:
            - cd macosapp && rm -rf outrig.iconset && mkdir -p outrig.iconset
            - cd macosapp && sips -z 16 16     assets/outrigapp-iconbase.png --out outrig.iconset/icon_16x16.png
            - cd macosapp && sips -z 32 32     assets/outrigapp-iconbase.png --out outrig.iconset/icon_16x16@2x.png
            - cd macosapp && sips -z 32 32     assets/outrigapp-iconbase.png --out outrig.iconset/icon_32x32.png
            - cd macosapp && sips -z 64 64     assets/outrigapp-iconbase.png --out outrig.iconset/icon_32x32@2x.png
            - cd macosapp && sips -z 128 128   assets/outrigapp-iconbase.png --out outrig.iconset/icon_128x128.png
            - cd macosapp && sips -z 256 256   assets/outrigapp-iconbase.png --out outrig.iconset/icon_128x128@2x.png
            - cd macosapp && sips -z 256 256   assets/outrigapp-iconbase.png --out outrig.iconset/icon_256x256.png
            - cd macosapp && sips -z 512 512   assets/outrigapp-iconbase.png --out outrig.iconset/icon_256x256@2x.png
            - cd macosapp && sips -z 512 512   assets/outrigapp-iconbase.png --out outrig.iconset/icon_512x512.png
            - cd macosapp && sips -z 1024 1024 assets/outrigapp-iconbase.png --out outrig.iconset/icon_512x512@2x.png
            - cd macosapp && iconutil -c icns outrig.iconset -o assets/outrig.icns
            - echo "✅ Created outrig.icns"

    release:tag:git:
        desc: Create a git tag after verifying versions match and git directory is clean
        vars:
            VERSION: "{{.CLI_ARGS}}"
        cmds:
            # Check if git directory is clean
            - |
                if [ -n "$(git status --porcelain)" ]; then
                  echo "❌ Error: Git directory is not clean. Please commit all changes before tagging."
                  exit 1
                fi
            # Check if server version matches
            - |
                SERVER_VERSION=$(grep 'var OutrigServerVersion = ' server/pkg/serverbase/serverbase.go | cut -d'"' -f2)
                if [ "$SERVER_VERSION" != "{{.VERSION}}" ]; then
                  echo "❌ Error: Server version ($SERVER_VERSION) does not match requested tag version ({{.VERSION}})"
                  echo "Run 'task updateversions {{.VERSION}}' first to update versions"
                  exit 1
                fi
            # Check if SDK version matches
            - |
                SDK_VERSION=$(grep 'const OutrigSDKVersion = ' pkg/config/config.go | cut -d'"' -f2)
                if [ "$SDK_VERSION" != "{{.VERSION}}" ]; then
                  echo "❌ Error: SDK version ($SDK_VERSION) does not match requested tag version ({{.VERSION}})"
                  echo "Run 'task updateversions {{.VERSION}}' first to update versions"
                  exit 1
                fi
            # Check if macOS app version matches
            - |
                APP_VERSION=$(grep 'OutrigAppVersion = ' macosapp/main-outrigapp.go | cut -d'"' -f2)
                if [ "$APP_VERSION" != "{{.VERSION}}" ]; then
                  echo "❌ Error: macOS app version ($APP_VERSION) does not match requested tag version ({{.VERSION}})"
                  echo "Run 'task updateversions {{.VERSION}}' first to update versions"
                  exit 1
                fi
            # Check if package.json version matches (without 'v' prefix)
            - |
                VERSION_NO_V=$(echo "{{.VERSION}}" | sed 's/^v//')
                PKG_VERSION=$(grep '"version": "' package.json | cut -d'"' -f4)
                if [ "$PKG_VERSION" != "$VERSION_NO_V" ]; then
                  echo "❌ Error: package.json version ($PKG_VERSION) does not match requested tag version ($VERSION_NO_V)"
                  echo "Run 'task updateversions {{.VERSION}}' first to update versions"
                  exit 1
                fi
            # Create the git tag
            - git tag -a {{.VERSION}} -m "Release {{.VERSION}}"
            - echo "✅ Created git tag {{.VERSION}}"
            - echo "To push the tag, run\n  git push origin {{.VERSION}}"

    release:tag:
        desc: Set version in files and create a git tag in one step
        vars:
            VERSION: "{{.CLI_ARGS}}"
        cmds:
            # Check if git directory is clean before making any changes
            - |
                if [ -n "$(git status --porcelain)" ]; then
                  echo "❌ Error: Git directory is not clean. Please commit all changes before releasing."
                  exit 1
                fi
            # Update versions in files
            - task: updateversions
              vars: { VERSION: "{{.VERSION}}" }
            # Only commit if there are changes
            - |
                if [ -n "$(git status --porcelain)" ]; then
                  git add server/pkg/serverbase/serverbase.go pkg/base/base.go package.json macosapp/main-outrigapp.go macosapp/assets/Info.plist
                  git commit -m "Bump version to {{.VERSION}}"
                  echo "✅ Committed version changes"
                else
                  echo "ℹ️ No changes to commit, versions already up to date"
                fi
            # Create the git tag
            - task: release:tag:git
              vars: { VERSION: "{{.VERSION}}" }
            - echo "✅ Version {{.VERSION}} released successfully"

    generate:appcast:
        desc: Generate appcast.xml file for a specific version
        vars:
            VERSION: "{{.CLI_ARGS}}"
        cmds:
            - |
                if [ -z "{{.VERSION}}" ]; then
                  echo "❌ Error: Version is required"
                  echo "Usage: task generate:appcast -- v0.6.0"
                  exit 1
                fi
            - |
                if [ -z "$SPARKLE_PRIVATE_KEY" ]; then
                  echo "❌ Error: SPARKLE_PRIVATE_KEY environment variable not set"
                  echo "Set it with: export SPARKLE_PRIVATE_KEY=your_base64_key"
                  exit 1
                fi
            - mkdir -p dist
            - cd server/cmd/generateappcast && go run main-generateappcast.go {{.VERSION}}
            - echo "✅ Generated appcast.xml for version {{.VERSION}}"

    generate:cask:
        desc: Generate Homebrew cask file for a specific version
        vars:
            VERSION: "{{.CLI_ARGS}}"
        cmds:
            - |
                if [ -z "{{.VERSION}}" ]; then
                  echo "❌ Error: Version is required"
                  echo "Usage: task generate:cask -- v0.6.0"
                  exit 1
                fi
            - mkdir -p dist
            - cd server/cmd/generatecask && go run main-generatecask.go {{.VERSION}}
            - echo "✅ Generated Homebrew cask for version {{.VERSION}}"
