// Copyright 2025, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { RpcClient } from "./rpc";

class RpcApiType {
    // command "droprequest" [call]
    DropRequestCommand(client: RpcClient, data: DropRequestData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("droprequest", data, opts);
    }

    // command "message" [call]
    MessageCommand(client: RpcClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("message", data, opts);
    }

    // command "searchrequest" [call]
    SearchRequestCommand(client: RpcClient, data: SearchRequestData, opts?: RpcOpts): Promise<SearchResultData> {
        return client.rpcCall("searchrequest", data, opts);
    }

    // command "streamupdate" [call]
    StreamUpdateCommand(client: RpcClient, data: StreamUpdateData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("streamupdate", data, opts);
    }

    // command "updatestatus" [call]
    UpdateStatusCommand(client: RpcClient, data: StatusUpdateData, opts?: RpcOpts): Promise<void> {
        return client.rpcCall("updatestatus", data, opts);
    }

}

export const RpcApi = new RpcApiType();
