name: Build Outrig Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag to release (e.g., v0.1.0)"
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  # When manually triggered, checkout the specified tag
                  ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
                  cache: true
                  cache-dependency-path: server/go.sum

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                  version: 3.42.1
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            # Dependencies and frontend build are handled by GoReleaser

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: "2.8.2"
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_SECRET }}
                  MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
                  MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
                  MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
                  MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
                  MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}

    build-macos-app:
        needs: goreleaser
        strategy:
            matrix:
                include:
                    - arch: amd64
                      runner: macos-14
                    - arch: arm64
                      runner: macos-latest
        runs-on: ${{ matrix.runner }}
        env:
            GOARCH: ${{ matrix.arch }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
                  cache: true
                  cache-dependency-path: server/go.sum

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install Node.js Dependencies
              run: npm ci

            - name: Install Go Task
              uses: arduino/setup-task@v2
              with:
                  version: 3.43.3
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install create-dmg
              run: brew install create-dmg

            - name: Import Codesign Certificate
              uses: apple-actions/import-codesign-certs@v3
              with:
                  p12-file-base64: ${{ secrets.MACOS_SIGN_P12 }}
                  p12-password: ${{ secrets.MACOS_SIGN_PASSWORD }}

            - name: Build macOS App Bundle
              run: task build:app-bundle

            - name: Sign App Bundle
              run: |
                  codesign --deep --force --options runtime \
                    --sign "Developer ID Application: Command Line Inc (M4LA8V687Y)" \
                    --timestamp \
                    ./dist/Outrig.app

            - name: Create DMG
              run: |
                  create-dmg \
                    --volname "Outrig" \
                    --window-pos 200 120 \
                    --window-size 600 400 \
                    --icon-size 100 \
                    --icon "Outrig.app" 175 190 \
                    --hide-extension "Outrig.app" \
                    --app-drop-link 425 190 \
                    Outrig-${{ matrix.arch }}.dmg \
                    ./dist

            - name: Decode and Write Notary API Key
              env:
                  MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
                  MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
              run: |
                  echo "$MACOS_NOTARY_KEY" | base64 --decode > AuthKey_${MACOS_NOTARY_KEY_ID}.p8

            - name: Submit DMG for Notarization
              env:
                  MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
                  MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
              run: |
                  set +e
                  submission_id=$(xcrun notarytool submit Outrig-${{ matrix.arch }}.dmg \
                      --key AuthKey_${MACOS_NOTARY_KEY_ID}.p8 \
                      --key-id "$MACOS_NOTARY_KEY_ID" \
                      --issuer "$MACOS_NOTARY_ISSUER_ID" \
                      --wait --output-format json | jq -r '.id')
                  NOTARY_EXIT_CODE=$?

                  xcrun notarytool log "$submission_id" \
                      --key AuthKey_${MACOS_NOTARY_KEY_ID}.p8 \
                      --key-id "$MACOS_NOTARY_KEY_ID" \
                      --issuer "$MACOS_NOTARY_ISSUER_ID"

                  exit $NOTARY_EXIT_CODE

            - name: Staple Notarization Ticket
              run: |
                  xcrun stapler staple Outrig-${{ matrix.arch }}.dmg

            - name: Get Draft Release Upload URL
              id: get_draft_release
              run: |
                  upload_url=$(gh release view ${{ github.ref_name }} --repo outrigdev/outrig --json uploadUrl -q '.uploadUrl')
                  echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload Asset to Draft Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.get_draft_release.outputs.upload_url }}
                  asset_path: ./Outrig-${{ matrix.arch }}.dmg
                  asset_name: Outrig-darwin-${{ matrix.arch }}-${{ github.ref_name }}.dmg
                  asset_content_type: application/x-apple-diskimage

            - name: Upload DMG as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dmg-${{ matrix.arch }}
                  path: ./Outrig-${{ matrix.arch }}.dmg

    generate-appcast:
        needs: build-macos-app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"

            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                  version: 3.43.3
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Download DMG Artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: dmg-*
                  path: ./dmg-artifacts

            - name: Organize DMG Files
              run: |
                  mkdir -p ./dmg-files
                  echo "Moving DMG files from artifact directories..."
                  find ./dmg-artifacts -name "*.dmg" -exec mv {} ./dmg-files/ \;
                  echo "Available DMG files:"
                  ls -la ./dmg-files/

            - name: Generate Appcast
              env:
                  SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}
                  DMG_FILES_PATH: ../../../dmg-files
              run: |
                  task generate:appcast -- ${{ github.ref_name }}

            - name: Get Draft Release Upload URL
              id: get_draft_release
              run: |
                  upload_url=$(gh release view ${{ github.ref_name }} --repo outrigdev/outrig --json uploadUrl -q '.uploadUrl')
                  echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Appcast to Draft Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.get_draft_release.outputs.upload_url }}
                  asset_path: ./dist/appcast.xml
                  asset_name: appcast.xml
                  asset_content_type: application/xml

            - name: Create PR for Appcast Update
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -e

                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  BRANCH_NAME="update-appcast-${{ github.ref_name }}"

                  git fetch origin gh-pages:gh-pages
                  git checkout gh-pages

                  git checkout -B "$BRANCH_NAME"

                  cp ./dist/appcast.xml ./appcast.xml

                  if [[ -z $(git status --porcelain) ]]; then
                      echo "No changes to appcast.xml; skipping PR."
                      exit 0
                  fi

                  git add appcast.xml
                  git commit -m "Update appcast.xml for ${{ github.ref_name }} release"
                  git push origin "$BRANCH_NAME" -f

                  gh pr create \
                      --base gh-pages \
                      --head "$BRANCH_NAME" \
                      --title "Update appcast.xml for ${{ github.ref_name }} Release" \
                      --body "Automated update of appcast.xml for release ${{ github.ref_name }}" \
                      || echo "PR already exists or no changes detected."

    update-homebrew-cask:
        needs: build-macos-app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"

            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                  version: 3.43.3
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Download DMG Artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: dmg-*
                  path: ./dmg-artifacts

            - name: Organize DMG Files
              run: |
                  mkdir -p ./dmg-files
                  echo "Moving DMG files from artifact directories..."
                  find ./dmg-artifacts -name "*.dmg" -exec mv {} ./dmg-files/ \;
                  echo "Available DMG files:"
                  ls -la ./dmg-files/

            - name: Generate Homebrew Cask
              env:
                  DMG_FILES_PATH: ../../../dmg-files
              run: |
                  task generate:cask -- ${{ github.ref_name }}

            - name: Create PR for Homebrew Cask Update
              env:
                  GH_TOKEN: ${{ secrets.HOMEBREW_SECRET }}
              run: |
                  set -e

                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  BRANCH_NAME="update-cask-${{ github.ref_name }}"

                  # Clone the homebrew-outrig repository using gh CLI for proper authentication
                  gh repo clone outrigdev/homebrew-outrig homebrew-repo
                  cd homebrew-repo

                  # Create new branch
                  git checkout -B "$BRANCH_NAME"

                  # Create Casks directory if it doesn't exist
                  mkdir -p Casks

                  # Copy the generated cask file
                  cp ../dist/outrig.rb Casks/outrig.rb

                  # Check if there are changes
                  if [[ -z $(git status --porcelain) ]]; then
                      echo "No changes to Homebrew cask; skipping PR."
                      exit 0
                  fi

                  # Commit and push changes
                  git add Casks/outrig.rb
                  git commit -m "Update Outrig cask for ${{ github.ref_name }} release"

                  # Configure git remote to use token authentication
                  git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/outrigdev/homebrew-outrig.git
                  git push origin "$BRANCH_NAME" -f

                  # Create PR
                  gh pr create \
                      --repo outrigdev/homebrew-outrig \
                      --base main \
                      --head "$BRANCH_NAME" \
                      --title "Update Outrig Cask for ${{ github.ref_name }} Release" \
                      --body "Automated update of Outrig cask for release ${{ github.ref_name }}" \
                      || echo "PR already exists or no changes detected."
